/**
 * Removes a document filed against a learner.
 *
 * There is no upload here. Every row in `student_documents` is a report card this app
 * generated - see the SF9 route, which files each card as it produces it - so the only thing a
 * registrar needs to do from outside that flow is take one back off a record when it was
 * generated by mistake.
 *
 * Downloads live at `documents/[docId]`.
 */

import { revalidatePath } from "next/cache";
import { deleteDocument, getDocument } from "@/lib/db/queries.ts";
import { requireUnlockedForApi } from "@/lib/auth/guard.ts";
import { deleteOriginal } from "@/lib/blob/store.ts";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function DELETE(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const auth = await requireUnlockedForApi();
  if (auth.response) return auth.response;

  const { id } = await params;
  const studentId = Number(id);
  const documentId = Number(new URL(request.url).searchParams.get("documentId"));
  if (!Number.isInteger(studentId) || !Number.isInteger(documentId)) {
    return new Response("Invalid id", { status: 400 });
  }

  /*
   * Ownership is checked BEFORE anything is removed.
   *
   * Reading it through `deleteDocument` and checking afterwards would have deleted the row
   * first and then refused - so a document id from another learner's record, passed through
   * this learner's URL, would be gone by the time the check said no.
   */
  const doc = await getDocument(documentId);
  if (!doc || doc.student_id !== studentId) {
    return new Response("Document not found", { status: 404 });
  }

  await deleteDocument(documentId);
  await deleteOriginal(doc.stored_path);

  revalidatePath(`/students/${studentId}`);
  return new Response(null, { status: 204 });
}
